export const dishvarity = [
    {
      id: 1,
      Image: require('../../assets/images/SwiggyImages/burger.jpg'),
      Image2: require('../../assets/images/SwiggyImages/aaloghobhi.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers7.jpg'),
      resturants: "Great Indian Vegitabbles by EatFit ",
      rating: "4.6 25-30 mins",
      menu: "Indian, Home Food, Healthy Food, Snacks ",
      location: "Sector 24",
      rst: 'Burger for you',
      one:'Burger',
      other:'Filter',
      offer:'45% off',
    },
    {
      id: 2,
      Image: require('../../assets/images/SwiggyImages/chole.jpg'),
      Image2: require('../../assets/images/SwiggyImages/paneer.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers8.jpg'),
      resturants: "McDonald's",
      rating: "4.4 15-20 mins",
      menu: "Fast Food, Healthy Food, Salads, Snacks, Desserts,Beverages ",
      location: "Sector 19",
      rst: 'Great Indian Chole',
      one:'Chole',
      other:'Sort By',
      offer:'55% off',
    },
    {
      id: 3,
      Image: require('../../assets/images/SwiggyImages/manchurian.jpg'),
      Image2: require('../../assets/images/SwiggyImages/fries.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers6.jpg'),
      resturants: "Yours Junction. ",
      rating: "4.7 20-25 mins",
      menu: "Waffle, Desserts, Ice Cream",
      location: "Sector 8B",
      rst: 'Mix veg near by you',
      one:'Manch',
      other:'Fast Delivery',
      offer:'60% off',
    },
    {
      id: 4,
      Image: require('../../assets/images/SwiggyImages/momos.jpg'),
      Image2: require('../../assets/images/SwiggyImages/mixfastfood.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers3.jpg'),
      resturants: "KFC. ",
      rating: "4.2 15-20 mins",
      menu: "Burgers, Fast Food, Rolls & Wraps",
      location: "Sector 8",
      rst: 'Momos as everybody likes',
      one:'Momos',
      other:'Offers',
      offer:'30% off',
    },
    {
      id: 5,
      Image: require('../../assets/images/SwiggyImages/roll.jpg'),
      Image2: require('../../assets/images/SwiggyImages/mixture.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers5.jpg'),
      resturants: "Great Food villa ",
      rating: "4.7 15-20 mins",
      menu: "Ice Cream, Desserts, Ice Cream Cakes",
      location: "East Chd",
      rst: 'Tastey & healthy Roti Roll',
      one:'Veg Roll',
      other:'Rating 4.0+',
      offer:'50% off',
    },
    {
      id: 6,
      Image: require('../../assets/images/SwiggyImages/noodles.jpg'),
      Image2: require('../../assets/images/SwiggyImages/chawmin.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers2.jpg'),
      resturants: "Subway Dishes ",
      rating: "4.3 30-35 mins",
      menu: "American, Fast Food",
      location: "Sector 22",
      rst: 'Noodles at minimun price',
      one:'Noodles',
      other:'Rs. 300-Rs. 600',
      offer:'60% off',
    },
    {
      id: 7,
      Image: require('../../assets/images/SwiggyImages/chole.jpg'),
      Image2: require('../../assets/images/SwiggyImages/roll.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers4.jpg'),
      resturants: "LunchBox Zone",
      rating: "4.3 30-35 mins",
      menu: "Biryani, North Indian, Desserts, Beverages",
      location: "Sector 22",
      rst: 'Vegis from Apni Rasoi',
      one:'Choler',
      other:'Less than Rs. 300',
      offer:'25% off',
    },
    {
      id: 8,
      Image: require('../../assets/images/SwiggyImages/sahipaneer.jpg'),
      Image2: require('../../assets/images/SwiggyImages/burger.jpg'),
      offerImg: require('../../assets/images/SwiggyImages/offers1.jpg'),
      resturants: "Pizza Zone ",
      rating: "4.3 30-35 mins",
      menu: "American, Fast Food",
      location: "Sector 22",
      rst: 'Sahi Paneer with great taste',
      one:'Paneer',
      other:'Pure Veg',
      offer:'35% off',
    },
  ];   